version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Adjust port mapping as needed
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=development  # Customize environment variables
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:13  # Change to your preferred database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=myapp
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data: 