services:
  remotejobbank:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Backend API port
      - "3000:3000"  # Frontend port
    environment:
      - NODE_ENV=development
    restart: unless-stopped
